### ISSUE TITLE
Missing dots

### ISSUE THREAD

**Issue by leon1995** [dikiaap/dotfiles#10]
### Describe the bug
Instead of this dots I get this `~/Downloads/dotfiles on  master` in my command line

I downloaded the theme from the .oh-my-zsh directory and copied the theme in the theme directory on my computer. Then i edited my `.zshrc` to enable `oxide`. Now I get this weird character when im in a git repositry. 

### Screenshots
[Screenshot](https://ibb.co/VQ0QF7k)

### Desktop

 - OS: MacOs 10.15.1
 - Package: oh-my-zsh

**Comment by dikiaap** [comment]
I suppose you mean the missing dots is that a weird character, right? Your problem may be the same as #9. You might want to change your font that supports the branch unicode ([Hack](https://github.com/source-foundry/Hack) and [Fira Code](https://github.com/tonsky/FiraCode)) or you can replace the branch unicode with something else.

**Comment by leon1995** [comment]
I changed the font to Fira and it worked so far, that I got the branch symbol [see here](https://ibb.co/rmjcxZq).
But as you can see, the three dots are still missing. is this intended?

**Comment by dikiaap** [comment]
No, it's not missing. You must have untracked/staged files so that the symbol appears.

Looks like your problem has been fixed, I'll close this issue.
