### ISSUE TITLE
Git icon not being shown on MacOS

### ISSUE THREAD

**Issue by Andrea-Arguello** [dikiaap/dotfiles#14]
### Describe the bug
<img width="254" alt="Screen Shot 2020-05-05 at 16 54 37" src="https://user-images.githubusercontent.com/31134106/81123857-51de3100-8ef1-11ea-83e9-5c3eca2e36c3.png">

### Expected behavior
I approached this theme because I find it very elegant and thought the icons were nice. However, the Git icon is not showing up on my terminal.

### Additional context
I only copy-pasted the code under the oh-my-zsh folder into the custom/themes on my machine, instead of running the install.sh. Should I do that instead? And if so, what would be an ideal place to clone the repo?

**Comment by Andrea-Arguello** [comment]
Found the issue, line 49 of the .zsh-theme
```FMT_VCS_STATUS="on %{$oxide_turquoise%} %b%u%c%{$oxide_reset_color%}"```

I can't see the icon so I guess it is an issue with MacOs. Guess I'll choose an icon and change it. Other than that, I'm very much in love with this theme

**Comment by dikiaap** [comment]
That's because it has a [private unicode character](https://en.wikipedia.org/wiki/Private_use_(unicode)). You can see: #9.

**Comment by Andrea-Arguello** [comment]
Thanks! I'll install one of the fonts suggested then :)
