### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by Windslab** [dikiaap/dotfiles#15]
Hi please help me to install it on my Arch Linux.

As me understood I just copy all files to my home.directory  and need some of to install. Please write to me.

```
sudo pacman -S pacname
```

The startx comand not workig...

**Comment by dikiaap** [comment]
Sorry, but you may have to install the package manually one by one, and I am not putting the automatic script to install unnecessary/unwanted packages to the users. A list of the packages also already listed in the README file, install the software what you need.

If you have a problem with `startx`, try `install.sh -r` for restoring your old dotfiles.
