### ISSUE TITLE
iTerm + Antigen crash installing Oxide Theme

### ISSUE THREAD

**Issue by ouchsaray** [dikiaap/dotfiles#2]
Hi!

I am trying to install Oxide theme but it crashs iTerm :/ . I used few commands to install it:

`
antigen theme dikiaap/dotfiles themes/oxide.zsh-theme
antigen theme dikiaap/dotfiles
`
Also import the zsh-theme to my ~/.oh-my-zsh/themes folder but it is not working either.

![screen shot 2018-03-09 at 10 31 27](https://user-images.githubusercontent.com/16121371/37203274-11616e3c-2385-11e8-8837-b7769fd098da.png)

![screen shot 2018-03-09 at 10 32 48](https://user-images.githubusercontent.com/16121371/37203334-419068d8-2385-11e8-8157-0a83ae4ee92f.png)

**Enviroment Details:**
MacOS High Sierra 10.12.6
iTerm2 Build 3.1.5
OhMyZsh Build zsh 5.2 (x86_64-apple-darwin16.0)  
Antigen v2.2.2

**Comment by dikiaap** [comment]
I think you missed `.oh-my-zsh` folder. Because `themes` is not in the root repo.

```
antigen theme dikiaap/dotfiles .oh-my-zsh/themes/oxide
antigen apply
``

**Comment by OuchSaray** [comment]
Solved, I just cleaned the lock file from antigen and pushing it to reinstall all the plugins/themes and now works. 

`rm ~/.antigen/.lock`

Cheers.

**Comment by dikiaap** [comment]
Nice.
