### ISSUE TITLE
colors base00 problem

### ISSUE THREAD

**Issue by Hkyx** [dikiaap/dotfiles#5]
Hi,

When tried to add some alias after dotfile install/sh the shell display that:
Warning: Color name "base00" is not defined

**Comment by dikiaap** [comment]
This seems Xresources issue

Try
- Rename ~/.Xresources to ~/.Xdefaults and login again
Or
- Create ~/.xprofile file with the following content and login again
```
SYSRESOURCES=/etc/X11/Xresources USRRESOURCES=$HOME/.Xresources
```

**Comment by Hkyx** [comment]
Hi, yes tried that but it didn't worked. 

Finally solved by removed the the configuration and install it again, don't really understood why it work with that but...
