### ISSUE TITLE
new alacritty window is the copy of the old alacritty

### ISSUE THREAD

**Issue by LoogCP** [dikiaap/dotfiles#7]
I'm a new guy for i3, and I live your dotfiles very much, it's so beautiful. there are some questions  I don't know how to solve them.
 when I open the second alacritty window(the same for the third or more), it is the copy of the first alacritty. two windows(or more )will change synchronously, one change, all change.

**Comment by dikiaap** [comment]
Thanks. That's because I attached tmux session automatically in alacritty config [`alacritty.yml#L1233`](https://github.com/dikiaap/dotfiles/blob/1e1391c3056fdd3acc121448dc8e264d2455d933/.alacritty/alacritty.yml#L1233).
I have fixed it in the next commit.
