### ISSUE TITLE
Oxide zsh theme: If branch changes after running a command other than `git` the pre-cmd metadata is wrong

### ISSUE THREAD

**Issue by atuttle** [dikiaap/dotfiles#8]
For example, I have an alias `--` that will run `git checkout -` (switch to the last branch that I was on). When I run `--` the branch switch happens, but because my command didn't include the string `git`, the wrong branch info is displayed:

![image](https://user-images.githubusercontent.com/46990/50576921-4e610400-0dea-11e9-80eb-e0da5f8dae07.png)

I believe that it happens in these lines:

https://github.com/dikiaap/dotfiles/blob/094efe1c543b7a10570cfccb1f77c213ffaf994b/.oh-my-zsh/themes/oxide.zsh-theme#L53-L66

**Comment by dikiaap** [comment]
I have tried your commands in different repositories and everything works well.

![x](https://user-images.githubusercontent.com/8542502/50577487-aa17a580-0e5b-11e9-9614-e1de4fc60e66.png)

Can you also post your .zshrc?

**Comment by dikiaap** [comment]
I have fixed the issue in new commit. Previously oxide.zsh-theme only detect changes and updated vcs status info by checking a user runs VCS's commands.

Now oxide.zsh-theme will always update vcs status info when a user runs any command in the current directory.
