### ISSUE TITLE
oh-my-zsh: unknown character in FMT_VCS_STATUS variable

### ISSUE THREAD

**Issue by imann24** [dikiaap/dotfiles#9]
### Describe the bug

Hi, there appears to be an unknown/undefined Unicode character in the `oh-my-zsh` theme: 

Comparing the observed behavior in reference to the screenshot on the `oh-my-zsh` Wiki page: 
![image](https://user-images.githubusercontent.com/5824989/66517866-c6a2d700-ea98-11e9-96f9-00232df75a9a.png)
-- https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes#oxide

### To Reproduce
1. Setup the `oh-my-zsh` theme
2. Observe terminal prompt has unknown char in it between "on" and branch name

### Expected behavior

Expect unicode character to match the one shown 

### Screenshots

![image](https://user-images.githubusercontent.com/5824989/66517942-e934f000-ea98-11e9-81bb-8dfa09b88f29.png)

### Desktop
 - OS: MacOS Mojave
 - Package: `oh-my-zsh` theme

**Comment by dikiaap** [comment]
That's a _private use_ unicode provided by a monospaced font I installed. I checked [Hack](https://github.com/source-foundry/Hack) and [Fira Code](https://github.com/tonsky/FiraCode), they both support the branch unicode.

![x](https://user-images.githubusercontent.com/8542502/66522606-078e0080-eb18-11e9-8719-162c20866606.png)

**Comment by imann24** [comment]
Appreciate the tip! I picked up `Fira Code` and am good to go.

**Comment by javl** [comment]
Putting this here as it might be somewhat related.
Apologies if I'm missing something obvious, but looking at [the example screenshot](https://camo.githubusercontent.com/97f30015b4fad8fe006805716b66bbab9d4ee117/68747470733a2f2f66696c65732e64696b696161702e69642f696d672f646f7466696c65732f69332e706e67) I see you're using icons in you workstation names. These seem to be coming from fontawesome (which I have installed), but you don't seem to define the usage of FA anywhere in any of the config files.
Any hint on what I might be missing?
